function gvjs_BX(a,b){gvjs_ET.call(this,a,b)}gvjs_t(gvjs_BX,gvjs_ET);gvjs_=gvjs_BX.prototype;gvjs_.Bp=function(a){a.style(gvjs_2w,0).style(gvjs_3w,1).style(gvjs_0w,.4).style(gvjs_1w,2);return a};gvjs_.Wq=function(a){a.style(gvjs_2w,null).style(gvjs_3w,null).style(gvjs_0w,null).style(gvjs_1w,null);return a};gvjs_.YV=function(a){var b=a.data().value.color;this.Bp(a).style(gvjs_du,b)};gvjs_.RV=function(a){var b=a.data().value.color;this.Bp(a).style(gvjs_du,gvjs_FT(b,this.$R,this.tB))};
gvjs_.IV=function(a){var b=a.data().value.color;this.Wq(a).style(gvjs_du,gvjs_GT(b,this.Eha,this.tB))};gvjs_.XV=function(a){var b=a.data().value.color;this.Wq(a).style(gvjs_du,b)};function gvjs_CX(a){this.m=a.options;this.D_=a.gn;this.Eh=a.kL;this.YP=a.oB.domain;this.a7=a.oB.target;this.qca=null!=a.pca?a.pca:1;this.Nra=null!=a.Mra?a.Mra:gvjs_1;this.Qv=this.layout()}gvjs_CX.prototype.By=function(){var a=[];gvjs_w(this.Qv,function(b){gvjs_Hc(a,b.F.list)});gvjs_Nc(a,function(a,c){return a.stack===c.stack?-gvjs_Mc(a.po,c.po):gvjs_Mc(a.stack,c.stack)});return a};
gvjs_CX.prototype.vC=function(){var a=[];gvjs_w(this.Qv,function(b){gvjs_u(b.groups,function(b,d){null!=b&&gvjs_u(b.$n,function(b,c){gvjs_Hc(a,gvjs_v(b.Vb.qk,function(a,b){var e=a.shape.data();return a.shape.clone().data({value:e,id:gvjs_vL(gvjs_vL(gvjs_vL(gvjs_vL(gvjs_xL(a.definition.Zn,a.definition.xF),gvjs_mS,a.definition.lj),gvjs_Ku,d),gvjs_ex,c),gvjs_lS,b+1)})}));gvjs_Hc(a,gvjs_v(b.Vb.yz,function(a,b){var e=a.shape.data();return a.shape.clone().data({value:e,id:gvjs_vL(gvjs_vL(gvjs_vL(gvjs_vL(gvjs_xL(a.definition.Zn,
a.definition.xF),gvjs_mS,a.definition.lj),gvjs_Ku,d),gvjs_ex,c),gvjs_lS,-b-1)})}))},this)},this)},this);return a};function gvjs_bka(a,b){if(1>=a)return[b];var c=0*(b.end-b.start),d=c/(a-1),c=(b.end-b.start-c)/a,e=[];b=b.start;for(var f=0;f<a;f++)e.push(new gvjs_H(b,b+c)),b+=c+d;return e}
function gvjs_cka(a,b,c,d){var e={range:b,definition:c,$n:[]},f=gvjs_bka(c.$n.length,b);gvjs_u(c.$n,function(a,b){var c={definition:a,range:f[b],height:{qk:0,yz:0},Vb:{qk:[],yz:[]}};e.$n.push(c);gvjs_u(a.Vb,function(a,e){a.Zn in d.index?d.list[d.index[a.Zn]].Vb.push(a):(d.index[a.Zn]=d.list.length,d.list.push({color:null,Zb:a.Zn,stack:b,po:e,Vb:[a]}),d.K6=Math.max(d.K6,b+1),d.wY=Math.max(d.wY,e+1));e=this.a7[a.QM];var f=e.scale,g=f.scale(f.sC()),f=c.range.start,h=c.height.qk+g,k=c.range.end-c.range.start,
l=a.value;if(isNaN(l)||null==l)e=null;else{var l=l-g,m=l+c.height.qk;0<=l?c.height.qk+=l:(h=-c.height.yz+g,m=-c.height.yz+l+g,c.height.yz-=l);a.Lt=k/2+c.range.start;a.jGa=m;gvjs_vL(gvjs_xL(a.Zn,a.xF),gvjs_mS,a.lj);g=new gvjs_D(h,f+k,h+l,f);g.top>g.bottom&&(m=g.top,g.top=g.bottom,g.bottom=m);null===e.range?e.range=new gvjs_H(g.top,g.bottom):(gvjs__g(e.range,g.top),gvjs__g(e.range,g.bottom));e=(new gvjs_zz(f,h,k,l)).setData(a)}e&&(0<=gvjs_K(gvjs_vz(e),gvjs_db)?c.Vb.qk:c.Vb.yz).push({definition:a,shape:e})},
this)},a);return e}
function gvjs_dka(a,b){var c={};if(gvjs_tc(a,function(a){return 0===a.groups.length}))return{};gvjs_u(a,function(a,b){gvjs_u(a.groups,function(a){c[a.lj]=b})});var d={},e={},f;for(f in b){var g=b[f],h=g.scale,g=gvjs_v(g.columns,function(b){return a[c[b]]}),k={qFa:h.bi(),type:g[0].type,scale:h,ig:{},groups:[]};e[f]=k;k.type in d||(d[k.type]=f);if(h.bi())for(var l=0;;l++){var m={$n:[]},n=gvjs_v(g,function(a){return a.groups[l]});if(!gvjs_sc(n,gvjs_Ob))break;gvjs_u(n,function(a){a.bh&&null==m.bh&&(m.bh=
a.bh);gvjs_Hc(m.$n,a.$n)});k.groups.push(m)}else{var p=[];gvjs_u(g,function(a){gvjs_u(a.groups,function(a){var b=gvjs_Kc(p,a,function(a,b){return h.Jx(a.bh,b.bh)});0>b?gvjs_Bc(p,{bh:a.bh,ig:gvjs_x(a.ig),$n:gvjs_Gc(a.$n)},-(b+1)):gvjs_Hc(p[b].$n,a.$n)})});k.groups=p}}return e}
function gvjs_eka(a,b,c,d){var e=a.YP[c],f=e.scale;f.bi()||gvjs_Nc(b.groups,function(a,b){a=a.na?a.bh:f.scale(a.bh);b=b.na?b.bh:f.scale(b.bh);return gvjs_Mc(a,b)});var g=Infinity,h=null;gvjs_u(b.groups,function(a){f.bi()&&(a.bh=f.add(a.bh),a.na=!0);a=a.na?a.bh:f.scale(a.bh);if(null!=a){if(null!==h){var b=a-h;0<b&&b<g&&(g=b)}h=a}});gvjs_4d(g)||(g=1);var k={list:[],index:{},K6:0,wY:0};c=gvjs_v(b.groups,function(a){var b=a.na?a.bh:f.scale(a.bh);if(null!=b){var c=g,d=b,b=b+c;switch(this.Nra){case gvjs_1:d-=
c/2,b-=c/2}c=(b-d)/2;d+=(1-this.qca)*c;b-=(1-this.qca)*c;d=new gvjs_H(d,b);null===e.range?e.range=d.clone():(c=e.range,c.start=Math.min(c.start,d.start),c.end=Math.max(c.end,d.end));return gvjs_cka(this,d,a,k)}},a);for(var l=0,m=k.K6;l<m;l++)for(var n=0,p=k.wY;n<p;n++)a.Eh.mu(String(l),String(n));var q=a.Eh.Sc();gvjs_u(k.list,function(a,b){var c=gvjs_Jg(gvjs_M(this.m,gvjs__w+(b+d)+".color",q.rq(a.stack,a.po))).hc;a.color=c;gvjs_u(a.Vb,function(a){a.color=c})},a);return{definition:b,F:k,groups:c}}
gvjs_CX.prototype.layout=function(){var a=gvjs_dka(this.D_,this.YP),b=0;return gvjs_Vc(a,function(a,d){a=gvjs_eka(this,a,d,b);b+=a.F.list.length;return a},this)};function gvjs_DX(a,b,c,d){gvjs_TT.call(this,a,b,c,d)}gvjs_t(gvjs_DX,gvjs_TT);gvjs_DX.prototype.Ai=function(){return gvjs_ji(this.options,gvjs_Bs,gvjs_cT,gvjs_i)===gvjs_d?gvjs_i:gvjs_d};
gvjs_DX.prototype.rpa=function(a,b,c,d){function e(a,b){return f?b:a}var f=gvjs_J(this.options,"stacked",!1),g=this.jj,h=a[String(c.lj)],k=g.getValue(d,c.lj);this.Ai();var l=e([0],c.F),m=[];gvjs_u(e(c.F,[0]),function(a){var e=[],n={};gvjs_u(l,function(l){l=(f?l:a).ms;var m=g.getValue(d,l),p=b[l],q=p.scale,r=p.name;r in n||(e.push({Vb:[]}),n[r]=e.length-1);r=e[n[r]].Vb;q.bi()&&null!=m&&(0===gvjs_JS(q).length&&q.add("",!0),q.add(m,!0));r.push({lj:c.lj,Zn:l,xF:d,ZP:h.name,QM:p.name,bh:k,uGa:m,color:null,
value:p.scale.scale(m),na:!0})});gvjs_u(e,function(a){m.push(a)})});return{lj:c.lj,bh:k,ig:c.ig,$n:m}};gvjs_DX.prototype.qpa=function(a,b,c){return{type:this.jj.X(c.lj),ig:c.ig,groups:gvjs_v(gvjs_Rc(this.jj.fa()),gvjs_s(this.rpa,this,a,b,c))}};
gvjs_DX.prototype.LQ=function(a,b,c){gvjs_w(a,function(a){a.expand=!1});gvjs_w(b,function(a){a.expand=!0});var d=this.Ai()===gvjs_i,e=d&&gvjs_sc(gvjs_0c(b),function(a){return b[a].Bk===gvjs_Ox}),f=d&&gvjs_sc(gvjs_0c(b),function(a){return b[a].Bk===gvjs_Ls}),g={},h;for(h in b)gvjs_u(b[h].columns,function(a){g[a]={name:h,scale:b[h].scale}});var k={};for(h in a)gvjs_u(a[h].columns,function(b){k[b]={name:h,scale:a[h].scale}});var l=gvjs_v(this.BP.gn,gvjs_s(this.qpa,this,k,g));return new gvjs_CX({options:this.options,
gn:l,oB:{domain:a,target:b},kL:c,pca:gvjs_$h(this.options,"groupSize"),IFa:!d||e,JFa:!d||f})};function gvjs_EX(a){gvjs_JL.call(this,a)}gvjs_t(gvjs_EX,gvjs_JL);gvjs_=gvjs_EX.prototype;gvjs_.lq=function(){return null};gvjs_.gh=function(){return gvjs_dT};gvjs_.xo=function(a,b,c,d){a=new gvjs_pS(this,a,0,c,d);a.St([gvjs_ws,gvjs_Gu,gvjs_Ow,gvjs_8R,gvjs_eS,gvjs_Vr,gvjs_Ur,gvjs_Ij]);return a};gvjs_.$m=function(a,b){return new gvjs_BX(a,b)};gvjs_.Ul=function(a,b,c,d){return new gvjs_DX(a,b,c,d)};
gvjs_.hs=function(a){return[new gvjs_yS([new gvjs_5(gvjs_nr)]),new gvjs_AS([new gvjs_5(gvjs_or),new gvjs_5(gvjs_pr)],gvjs_M(a,gvjs_Uw)===gvjs_vb),new gvjs_zS([new gvjs_5(gvjs_nr),new gvjs_5(gvjs_or),new gvjs_5(gvjs_pr),new gvjs_5(gvjs_iS)]),new gvjs_CS([new gvjs_5(gvjs_or)])]};gvjs_.YH=function(a,b){null!=this.dh?this.dh.update(a,b):this.dh=new gvjs_bA(this.ga,a,b,[gvjs_Lr,gvjs_kS])};gvjs_l(gvjs_Sk,gvjs_EX,void 0);gvjs_EX.convertOptions=function(a){var b=new gvjs_Oh([a]);a=gvjs_jT(a);b=gvjs_bi(b,gvjs_9v);null!=b&&(a.bars=b===gvjs_i?gvjs_d:gvjs_i);return a};gvjs_EX.prototype.draw=gvjs_EX.prototype.draw;gvjs_EX.prototype.clearChart=gvjs_EX.prototype.fc;gvjs_EX.prototype.getSelection=gvjs_EX.prototype.getSelection;gvjs_EX.prototype.setSelection=gvjs_EX.prototype.setSelection;